import mongoose from "mongoose";

const reportSchema = new mongoose.Schema(
    {
        // ==========================================
        // REPORT TYPE
        // ==========================================

        reportType: {
            type: String,
            enum: [
                "event_overview",
                "registration",
                "exhibitor",
                "booth",
                "visitor",
                "feedback",
                "complete_event",

                // Exhibitor-specific reports
                "my_exhibitor_overview",
                "my_booth",
                "my_visitors",
                "my_feedback"
            ],
            required: true
        },


        // ==========================================
        // EVENT
        // ==========================================

        event: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Event",
            required: true
        },


        // ==========================================
        // USER WHO GENERATED THE REPORT
        // ==========================================

        generatedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true
        },


        // ==========================================
        // ROLE OF USER
        // ==========================================

        generatedByRole: {
            type: String,
            enum: [
                "admin",
                "organizer",
                "exhibitor"
            ],
            required: true
        },


        // ==========================================
        // FILE FORMAT
        // ==========================================

        format: {
            type: String,
            enum: [
                "pdf",
                "xlsx",
                "docx"
            ],
            required: true
        },


        // ==========================================
        // FILE INFORMATION
        // ==========================================

        fileName: {
            type: String,
            required: true,
            trim: true
        },

        cloudinaryUrl: {
            type: String,
            required: true
        },

        cloudinaryPublicId: {
            type: String,
            required: true
        }
    },
    {
        timestamps: true
    }
);


// ==========================================
// INDEXES
// ==========================================

// Quickly find reports for an event
reportSchema.index({
    event: 1,
    createdAt: -1
});


// Quickly find reports generated by a user
reportSchema.index({
    generatedBy: 1,
    createdAt: -1
});


// Quickly filter reports by type
reportSchema.index({
    reportType: 1,
    createdAt: -1
});


const Report = mongoose.model(
    "Report",
    reportSchema
);

export default Report;