import PDFDocument from "pdfkit";


// ==========================================
// GENERATE PDF REPORT
// ==========================================

const generatePdfReport = ({
    title,
    event,
    sections = []
}) => {

    return new Promise((resolve, reject) => {

        try {

            const doc = new PDFDocument({
                margin: 50
            });

            const chunks = [];

            doc.on("data", (chunk) => {
                chunks.push(chunk);
            });

            doc.on("end", () => {

                const buffer = Buffer.concat(chunks);

                resolve(buffer);

            });

            doc.on("error", reject);


            // ==========================================
            // HEADER
            // ==========================================

            doc
                .fontSize(22)
                .font("Helvetica-Bold")
                .text("EventSphere");

            doc
                .moveDown(0.5)
                .fontSize(18)
                .text(title);

            doc
                .moveDown(0.5)
                .fontSize(11)
                .font("Helvetica")
                .text(`Event: ${event?.title || "N/A"}`);

            if (event?.category) {
                doc.text(`Category: ${event.category}`);
            }

            if (event?.location) {
                doc.text(`Location: ${event.location}`);
            }

            if (event?.startDate) {
                doc.text(
                    `Start Date: ${new Date(event.startDate).toLocaleString()}`
                );
            }

            if (event?.endDate) {
                doc.text(
                    `End Date: ${new Date(event.endDate).toLocaleString()}`
                );
            }


            doc.moveDown(1);

            // ==========================================
            // SECTIONS
            // ==========================================

            sections.forEach((section) => {

                doc
                    .fontSize(15)
                    .font("Helvetica-Bold")
                    .text(section.title);

                doc.moveDown(0.3);

                doc
                    .fontSize(10)
                    .font("Helvetica");


                if (section.data && typeof section.data === "object") {

                    Object.entries(section.data).forEach(
                        ([key, value]) => {

                            const formattedKey =
                                formatLabel(key);

                            const formattedValue =
                                formatValue(value);

                            doc.text(
                                `${formattedKey}: ${formattedValue}`
                            );
                        }
                    );

                }


                if (section.rows && Array.isArray(section.rows)) {

                    section.rows.forEach((row) => {

                        doc
                            .moveDown(0.2)
                            .font("Helvetica-Bold")
                            .text(row.title || "Item");

                        doc.font("Helvetica");

                        Object.entries(row)
                            .filter(([key]) => key !== "title")
                            .forEach(([key, value]) => {

                                doc.text(
                                    `${formatLabel(key)}: ${formatValue(value)}`
                                );

                            });

                    });

                }

                doc.moveDown(0.8);

            });


            // ==========================================
            // FOOTER
            // ==========================================

            doc
                .fontSize(8)
                .fillColor("gray")
                .text(
                    `Generated by EventSphere on ${new Date().toLocaleString()}`,
                    50,
                    doc.page.height - 40,
                    {
                        align: "center"
                    }
                );


            doc.end();

        } catch (error) {

            reject(error);

        }

    });

};


// ==========================================
// FORMAT LABEL
// ==========================================

const formatLabel = (value) => {

    return String(value)
        .replace(/([A-Z])/g, " $1")
        .replace(/^./, (char) => char.toUpperCase())
        .trim();

};


// ==========================================
// FORMAT VALUE
// ==========================================

const formatValue = (value) => {

    if (value === null || value === undefined) {
        return "N/A";
    }

    if (Array.isArray(value)) {
        return value
            .map(item => formatValue(item))
            .join(", ");
    }

    if (
        typeof value === "object" &&
        !(value instanceof Date)
    ) {
        return JSON.stringify(value);
    }

    return String(value);

};


export default generatePdfReport;